"""
Training Module - Phase 4
CPCS432 Assignment 5

This module handles Naive Bayes Training & Internal Evaluation:
1. Loads preprocessed artifacts from Phase 3.
2. Splits data into Train/Validation sets (80/20) .
3. Trains Multinomial Naive Bayes with Laplace smoothing .
4. Evaluates performance and inspects errors .
5. Saves the final model .
"""

import os
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction import DictVectorizer

# Import path config from your existing utils
from utils import OUTPUTS_DIR

def load_phase3_artifacts():
    """Loads the pickle files generated by the Phase 3 script."""
    print("[INFO] Loading Phase 3 artifacts from 'outputs/'...")
    
    try:
        # Load TF-IDF vectors (List of Dictionaries)
        with open(os.path.join(OUTPUTS_DIR, 'tfidf_vectors.pkl'), 'rb') as f:
            tfidf_vectors = pickle.load(f)

        # Load Labels
        with open(os.path.join(OUTPUTS_DIR, 'labels.pkl'), 'rb') as f:
            labels = pickle.load(f)

        # Load DataFrame (needed for error inspection)
        df_path = os.path.join(OUTPUTS_DIR, 'dataset_with_preprocessing.pkl')
        df = pd.read_pickle(df_path)
        
        print(f"[✓] Loaded {len(tfidf_vectors)} documents.")
        return tfidf_vectors, labels, df
        
    except FileNotFoundError as e:
        print(f"[ERROR] Could not load Phase 3 data: {e}")
        print("Please run your Phase 3 training script first.")
        return None, None, None

def run_phase4():
    print("="*70)
    print("PHASE 4: Naive Bayes Training & Internal Evaluation")
    print("="*70)

    # 1. Load Data
    tfidf_vectors, labels, df = load_phase3_artifacts()
    if tfidf_vectors is None:
        return

    # 2. Vector Conversion
    # Your custom TF-IDF (Phase 3) produced a list of dictionaries.
    # Sklearn's MultinomialNB requires a numerical matrix.
    print("\n[INFO] Converting dictionary vectors to matrix...")
    dict_vectorizer = DictVectorizer(sparse=True)
    X_matrix = dict_vectorizer.fit_transform(tfidf_vectors)
    
    # 3. Data Splitting
    # "Split available labeled data into train/validation sets (e.g., 80/20 stratified split)." 
    print("[INFO] Splitting data (80% Train, 20% Validation)...")
    X_train, X_val, y_train, y_val, idx_train, idx_val = train_test_split(
        X_matrix, 
        labels, 
        df.index, # Track original indices for error inspection
        test_size=0.2, 
        stratify=labels, 
        random_state=42
    )
    print(f"  Train: {X_train.shape[0]} | Validation: {X_val.shape[0]}")

    # 4. Train Model
    # "Train a Naive Bayes classifier... Apply Laplace/add-one smoothing" 
    #Use ComplementNB to handle the Sports/Economy imbalance
    print("\n[INFO] Training Complement Naive Bayes (alpha=1.0)...")
    clf = ComplementNB(alpha=1.0, fit_prior=False) # alpha=1.0 implements Laplace smoothing
    clf.fit(X_train, y_train)

    # 5. Evaluate
    # "Predict on validation set and compute accuracy" 
    print("\n[INFO] Evaluating model...")
    y_pred = clf.predict(X_val)
    accuracy = accuracy_score(y_val, y_pred)
    
    print(f"\n>> Validation Accuracy: {accuracy:.4f}")
    print("-" * 60)
    print("Classification Report:")
    print(classification_report(y_val, y_pred))

    # 6. Error Inspection
    # "Inspect misclassified examples to understand typical errors." 
    print("\n[INFO] Inspecting Misclassified Examples...")
    
    errors = []
    for i, (true_lab, pred_lab) in enumerate(zip(y_val, y_pred)):
        if true_lab != pred_lab:
            original_idx = idx_val[i]
            filename = df.loc[original_idx, 'filename']
            snippet = df.loc[original_idx, 'text'][:100].replace('\n', ' ')
            errors.append({
                'filename': filename,
                'true': true_lab,
                'pred': pred_lab,
                'snippet': snippet
            })

    # Print first 5 errors to console
    for err in errors[:5]:
        print(f"  [x] {err['filename']}: True={err['true']} | Pred={err['pred']}")

    # 7. Save Deliverables
    # "Serialize and save the final chosen Naive Bayes model as pkl" 
    print("\n[INFO] Saving Phase 4 Deliverables...")
    
    # Save Model
    model_path = os.path.join(OUTPUTS_DIR, 'nb_model.pkl')
    with open(model_path, 'wb') as f:
        pickle.dump(clf, f)
    print(f"[✓] Saved Model: {model_path}")
    
    # Save DictVectorizer (Required to transform new data during testing)
    # We must save this because we need to map words to the exact same matrix columns later.
    dv_path = os.path.join(OUTPUTS_DIR, 'dict_vectorizer.pkl')
    with open(dv_path, 'wb') as f:
        pickle.dump(dict_vectorizer, f)
    print(f"[✓] Saved Vectorizer Helper: {dv_path}")

    # Save Report
    # "Brief validation results (accuracy and any other metric) written in Notion." 
    report_path = os.path.join(OUTPUTS_DIR, 'validation_report.txt')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write("Phase 4 Validation Report\n")
        f.write("=========================\n")
        f.write(f"Accuracy: {accuracy:.4f}\n\n")
        f.write("Misclassified Examples:\n")
        for err in errors:
            f.write(f"File: {err['filename']}\n")
            f.write(f"  True: {err['true']} -> Pred: {err['pred']}\n")
            f.write(f"  Snippet: {err['snippet']}...\n\n")
            
    print(f"[✓] Saved Report: {report_path}")
    print("\n" + "="*70)
    print("PHASE 4 COMPLETE")
    print("="*70)

if __name__ == "__main__":
    run_phase4()
